name: Deploy Strapi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            set -e
            cd /opt/strapi/universa-strapi-project
            git fetch origin main
            git reset --hard origin/main
            sudo docker compose up -d --build
            sudo docker image prune -f
            sudo docker compose ps
            sudo docker compose logs --tail=50 strapi